name: CI Pipeline
on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ruff linter
        uses: astral-sh/ruff-action@v2
        with:
          args: "check ."

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services with Docker Compose
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB_AUTH: auth
          POSTGRES_DB_UNIVERSITY: university
          AUTH_SERVICE_INTERNAL_URL: http://auth-service:8000
          AUTH_SERVICE_API_URL: http://127.0.0.1:8000
          UNIVERSITY_SERVICE_INTERNAL_URL: http://university-service:8000
          UNIVERSITY_SERVICE_API_URL: http://127.0.0.1:8001
        run: docker compose up -d

      - name: Create image api-test
        run: docker build -t api-tests .

      - name: run api-tests
        run: |
          mkdir -p allure-results
          docker run --network host \
          -v ${{ github.workspace }}/allure-results:/app/allure-results \
          -e AUTH_URL=http://127.0.0.1:8000 \
          -e UNIVERSITY_URL=http://127.0.0.1:8001 \
          api-tests --alluredir=allure-results tests/ -s

      - name: Sanitize Allure Results (Remove JWT)
        if: always()
        run: |
          if [ -d "${{ github.workspace }}/allure-results" ]; then
            echo "Cleaning JWT tokens from Allure JSON files..."
            find ${{ github.workspace }}/allure-results -type f -name "*.json" -exec sed -i -E 's/eyJhbGciOi[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/ [MASKED_JWT] /g' {} +
          fi

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 1


  deploy-reports:
    needs: integration-tests
    if: always() && (needs.integration-tests.result == 'success' || needs.integration-tests.result == 'failure')
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Generate Allure report
        run: |
          npm install -g allure-commandline
          allure generate ./allure-results -o ./allure-report --clean

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          keep_files: false
